sonar.projectKey=insureflow
sonar.projectName=InsureFlow — Agentic AI Platform
sonar.projectVersion=1.0
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.source=21
sonar.host.url=http://localhost:9000
sonar.exclusions=\
  **/dto/**,\
  **/config/**,\
  **/InsureflowApplication.java,\
  **/migration/**,\
  **/entity/**,\
  **/model/**
sonar.coverage.jacoco.xmlReportPaths=\
  target/site/jacoco/jacoco.xml
