-- Requires pgvector extension (already enabled)
CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS past_claims (
    id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_name             VARCHAR(100),
    description             TEXT,
    claim_type              VARCHAR(50),
    parts_damaged           TEXT,
    estimated_amount        DECIMAL(10,2),
    decision                VARCHAR(30),
    rejection_reason        TEXT,
    contract_type           VARCHAR(50),
    fraud_score             DECIMAL(3,2),
    processing_time_seconds INT,
    claim_date              DATE,
    embedding               vector(1024)
);

CREATE INDEX IF NOT EXISTS idx_past_claims_claim_type ON past_claims (claim_type);
CREATE INDEX IF NOT EXISTS idx_past_claims_decision   ON past_claims (decision);

-- ─────────────────────────────────────────────────────────────────────────────
-- 100 SYNTHETIC PAST CLAIMS  (45 VEHICLE_DAMAGE | 30 THEFT | 25 PROPERTY_DAMAGE)
-- Decision split : ~60 APPROVED | ~20 PENDING_REVIEW | ~20 REJECTED
-- Rejected claims always have rejection_reason
-- fraud_score > 0.70 always REJECTED
-- ─────────────────────────────────────────────────────────────────────────────
INSERT INTO past_claims
    (client_name, description, claim_type, parts_damaged, estimated_amount,
     decision, rejection_reason, contract_type, fraud_score, processing_time_seconds, claim_date)
VALUES

-- ═══ VEHICLE_DAMAGE (45) ═══

-- APPROVED (27)
('Mohamed Ben Ali',        'Collision frontale avec un autre véhicule sur l''autoroute A1. Le pare-choc avant, le capot et le phare gauche sont endommagés.',                                     'VEHICLE_DAMAGE', 'pare-choc avant, capot, phare gauche',          4200.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.08, 5400,  '2024-01-15'),
('Fatma Trabelsi',         'Accrochage dans un parking : portière avant droite enfoncée et rétroviseur cassé.',                                                                                    'VEHICLE_DAMAGE', 'portière avant droite, rétroviseur',             1800.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.12, 3200,  '2024-01-22'),
('Karim Jendoubi',         'Sortie de route sur route mouillée : aile avant gauche froissée et pare-brise fissuré.',                                                                              'VEHICLE_DAMAGE', 'aile avant gauche, pare-brise',                  2900.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.10, 4100,  '2024-02-03'),
('Sonia Gharbi',           'Tamponnement par l''arrière : pare-choc arrière enfoncé, coffre déformé.',                                                                                           'VEHICLE_DAMAGE', 'pare-choc arrière, coffre',                      2200.00,  'APPROVED',        NULL, 'TIERS_PLUS',   0.09, 3800,  '2024-02-18'),
('Nabil Chaouachi',        'Grêle violente : nombreuses bosses sur le capot, le toit et la carrosserie.',                                                                                         'VEHICLE_DAMAGE', 'capot, toit, carrosserie',                       3500.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.05, 4700,  '2024-03-07'),
('Asma Boughzala',         'Choc latéral droit en intersection : portière arrière droite et aile arrière droite abîmées.',                                                                        'VEHICLE_DAMAGE', 'portière arrière droite, aile arrière droite',   2600.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.11, 4300,  '2024-03-19'),
('Imed Dridi',             'Accrochage dans une ruelle étroite : pare-choc avant gauche rayé et phare avant droit fissuré.',                                                                      'VEHICLE_DAMAGE', 'pare-choc avant, phare avant droit',              1400.00,  'APPROVED',        NULL, 'TIERS_PLUS',   0.07, 2900,  '2024-04-02'),
('Rania Hamdi',            'Collision avec un poteau : aile avant droite déformée, phare droit brisé et capot plié.',                                                                             'VEHICLE_DAMAGE', 'aile avant droite, phare droit, capot',           3100.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.13, 5100,  '2024-04-14'),
('Tahar Mansouri',         'Véhicule renversé sur une chaussée verglacée. Toit enfoncé, plusieurs vitres brisées, portières bloquées.',                                                           'VEHICLE_DAMAGE', 'toit, vitres, portières',                        9800.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.15, 7200,  '2024-04-28'),
('Leila Boukadida',        'Choc frontal modéré au feu rouge : pare-choc avant et calandre endommagés.',                                                                                          'VEHICLE_DAMAGE', 'pare-choc avant, calandre',                      1600.00,  'APPROVED',        NULL, 'TIERS_PLUS',   0.06, 2600,  '2024-05-05'),
('Zied Arfaoui',           'Aile arrière gauche enfoncée dans un parking souterrain par un autre conducteur.',                                                                                    'VEHICLE_DAMAGE', 'aile arrière gauche',                             1100.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.08, 2200,  '2024-05-20'),
('Olfa Sfar',              'Pare-brise fissuré de part en part suite à un caillou projeté sur l''autoroute.',                                                                                     'VEHICLE_DAMAGE', 'pare-brise',                                      900.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.04, 1800,  '2024-06-03'),
('Hedi Khalfallah',        'Collision arrière sur autoroute : pare-choc arrière, hayon et feux arrière détruits.',                                                                                'VEHICLE_DAMAGE', 'pare-choc arrière, hayon, feux arrière',          3400.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.10, 5600,  '2024-06-17'),
('Manel Touibi',           'Accrochage léger côté conducteur : portière avant gauche rayée et rétroviseur plié.',                                                                                 'VEHICLE_DAMAGE', 'portière avant gauche, rétroviseur',              1200.00,  'APPROVED',        NULL, 'TIERS_PLUS',   0.09, 2400,  '2024-07-01'),
('Yassine Ben Romdhane',   'Choc frontal violent contre un muret : pare-choc avant, phares, capot et moteur endommagés.',                                                                         'VEHICLE_DAMAGE', 'pare-choc avant, phares, capot, moteur',          8500.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.17, 8400,  '2024-07-14'),
('Houda Baccouche',        'Grêle sur capot et ailes : multiples impacts, peinture abîmée.',                                                                                                     'VEHICLE_DAMAGE', 'capot, ailes',                                   2100.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.06, 3500,  '2024-07-28'),
('Slim Ammar',             'Véhicule touché par un arbre tombé pendant une tempête : toit enfoncé, pare-brise brisé.',                                                                            'VEHICLE_DAMAGE', 'toit, pare-brise',                               5200.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.08, 6300,  '2024-08-09'),
('Mariem Khedher',         'Sortie de route dans un virage : pare-choc avant, aile gauche et jante endommagés.',                                                                                  'VEHICLE_DAMAGE', 'pare-choc avant, aile gauche, jante',             3000.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.12, 4800,  '2024-08-22'),
('Ramzi Laabidi',          'Tamponnement au carrefour : dommages sur le côté droit du véhicule, portières droites et aile.',                                                                      'VEHICLE_DAMAGE', 'portières droites, aile droite',                  2800.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.10, 4200,  '2024-09-04'),
('Ines Jeridi',            'Voiture rayée sur tout le côté gauche dans une rue commerçante.',                                                                                                     'VEHICLE_DAMAGE', 'flanc gauche',                                    800.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.07, 2000,  '2024-09-17'),
('Bilel Hamrouni',         'Choc frontal sur un camion en marche arrière : capot, pare-choc avant et phares cassés.',                                                                             'VEHICLE_DAMAGE', 'capot, pare-choc avant, phares',                  3700.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.09, 5000,  '2024-10-01'),
('Sabrine Ben Salah',      'Collision légère dans une sortie de garage : pare-choc avant rayé et légèrement enfoncé.',                                                                            'VEHICLE_DAMAGE', 'pare-choc avant',                                 700.00,  'APPROVED',        NULL, 'TIERS_PLUS',   0.05, 1600,  '2024-10-15'),
('Montassar Chebbi',       'Accrochage sur voie rapide : aile avant droite et portière avant droite enfoncées.',                                                                                  'VEHICLE_DAMAGE', 'aile avant droite, portière avant droite',        2400.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.11, 3900,  '2024-10-28'),
('Dorsaf Riahi',           'Inondation du moteur suite aux pluies torrentielles de Nabeul.',                                                                                                      'VEHICLE_DAMAGE', 'moteur, habitacle',                               6500.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.10, 7800,  '2024-11-10'),
('Adel Gaidi',             'Choc arrière à l''arrêt : pare-choc arrière et malle enfoncés.',                                                                                                     'VEHICLE_DAMAGE', 'pare-choc arrière, malle',                        1900.00,  'APPROVED',        NULL, 'TIERS_PLUS',   0.08, 3100,  '2024-11-23'),
('Wafa Mejri',             'Rayures profondes sur tout le côté droit suite à un accrochage dans une ruelle.',                                                                                     'VEHICLE_DAMAGE', 'flanc droit, portière droite',                    1300.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.06, 2700,  '2024-12-05'),
('Khaled Trabelsi',        'Accident de nuit : collision frontale avec un animal, capot et radiateur endommagés.',                                                                                'VEHICLE_DAMAGE', 'capot, radiateur, pare-choc avant',               2700.00,  'APPROVED',        NULL, 'TOUS_RISQUES', 0.09, 4400,  '2024-12-18'),

-- PENDING_REVIEW (9)
('Fethi Oueslati',         'Sinistre allégué lors d''un déplacement professionnel. Pare-choc avant et capot abîmés, aucun témoin.',                                                               'VEHICLE_DAMAGE', 'pare-choc avant, capot',                          3800.00,  'PENDING_REVIEW',  NULL, 'TOUS_RISQUES', 0.38, 5800,  '2024-02-25'),
('Amel Najar',             'Véhicule endommagé sur parking privé. Plusieurs éléments touchés, devis élevé.',                                                                                      'VEHICLE_DAMAGE', 'portières, capot, aile',                          7200.00,  'PENDING_REVIEW',  NULL, 'TOUS_RISQUES', 0.45, 6500,  '2024-05-12'),
('Riadh Ben Hassen',       'Accrochage à grande vitesse sur autoroute A3, dommages étendus sur le flanc droit.',                                                                                  'VEHICLE_DAMAGE', 'flanc droit, toit, portières droites',             11500.00,  'PENDING_REVIEW',  NULL, 'TOUS_RISQUES', 0.29, 9200,  '2024-06-30'),
('Noura Zouaoui',          'Choc frontal avec un bus : pare-choc avant, capot, phares, moteur suspects.',                                                                                         'VEHICLE_DAMAGE', 'pare-choc avant, capot, moteur',                  16200.00,  'PENDING_REVIEW',  NULL, 'TOUS_RISQUES', 0.32, 9800,  '2024-08-14'),
('Samir Bahri',            'Multi-impact suite à un carambolage sur A1 : carrosserie latérale gauche très endommagée.',                                                                           'VEHICLE_DAMAGE', 'flanc gauche, ailes, portières',                   9400.00,  'PENDING_REVIEW',  NULL, 'TOUS_RISQUES', 0.41, 8600,  '2024-09-28'),
('Naima Ben Fredj',        'Véhicule retrouvé vandalisé après une nuit dans la rue. État général dégradé.',                                                                                       'VEHICLE_DAMAGE', 'carrosserie, vitres, intérieur',                   5100.00,  'PENDING_REVIEW',  NULL, 'TOUS_RISQUES', 0.35, 6200,  '2024-10-20'),
('Issam Karray',           'Collision frontale multi-éléments : capot, pare-choc, phares, calandre, radiateur.',                                                                                  'VEHICLE_DAMAGE', 'capot, pare-choc, phares, radiateur',              12800.00,  'PENDING_REVIEW',  NULL, 'TOUS_RISQUES', 0.28, 10200, '2024-11-05'),
('Sonia Dridi',            'Sortie de route à grande vitesse. Multiples dommages structurels, expertise nécessaire.',                                                                             'VEHICLE_DAMAGE', 'châssis, toit, moteur, portières',                 17500.00,  'PENDING_REVIEW',  NULL, 'TOUS_RISQUES', 0.52, 12400, '2024-12-01'),
('Tarek Boughdir',         'Accrochage dans une zone non couverte géographiquement. Dossier incomplet.',                                                                                          'VEHICLE_DAMAGE', 'aile avant, portière avant',                       2300.00,  'PENDING_REVIEW',  NULL, 'TIERS_PLUS',   0.25, 4600,  '2025-01-08'),

-- REJECTED (9) — fraud_score > 0.70 or policy violation
('Lotfi Ghannouchi',       'Déclaration d''un sinistre datant de plus de 6 mois après les faits. Dommages non documentés.',                                                                       'VEHICLE_DAMAGE', 'carrosserie latérale',                             4500.00,  'REJECTED', 'Sinistre déclaré hors délai contractuel de 5 jours.', 'TIERS_PLUS',   0.78, 3000,  '2024-03-10'),
('Mondher Kasmi',          'Photos fournies ne correspondent pas au véhicule assuré. VIN différent.',                                                                                             'VEHICLE_DAMAGE', 'pare-choc, capot',                                5200.00,  'REJECTED', 'Fraude identifiée : photos d''un véhicule tiers, VIN incohérent.', 'TOUS_RISQUES', 0.91, 2400,  '2024-04-20'),
('Hajer Tlili',            'Véhicule assuré en tiers simple, demande de remboursement pour dommages propres non couverts.',                                                                        'VEHICLE_DAMAGE', 'capot, aile avant droite',                        3100.00,  'REJECTED', 'Garantie insuffisante : contrat tiers simple ne couvre pas les dommages propres.', 'TIERS_SIMPLE', 0.22, 2100,  '2024-05-28'),
('Ridha Boussaid',         'Sinistre survenu hors de la période de validité du contrat d''assurance.',                                                                                            'VEHICLE_DAMAGE', 'toit, portières',                                 6800.00,  'REJECTED', 'Contrat expiré à la date du sinistre.', 'TOUS_RISQUES', 0.55, 1800,  '2024-07-08'),
('Sana Baccar',            'Incohérence entre la description du sinistre et les dommages constatés par l''expert.',                                                                                'VEHICLE_DAMAGE', 'flanc gauche, aile',                               4100.00,  'REJECTED', 'Dommages préexistants non liés à l''incident déclaré.', 'TOUS_RISQUES', 0.81, 2700,  '2024-08-30'),
('Faouzi Hamdi',           'Tentative de gonflement du montant via double facturation de pièces détachées.',                                                                                      'VEHICLE_DAMAGE', 'pare-choc arrière, feux, jantes',                  8900.00,  'REJECTED', 'Fraude : double soumission de factures de réparation identiques.', 'TOUS_RISQUES', 0.93, 3100,  '2024-09-22'),
('Azza Belhadj',           'Conducteur non désigné au contrat lors du sinistre.',                                                                                                                 'VEHICLE_DAMAGE', 'pare-choc avant, capot',                           3600.00,  'REJECTED', 'Conducteur non autorisé : exclusion contractuelle applicable.', 'TIERS_PLUS',   0.40, 2000,  '2024-10-10'),
('Walid Chiha',            'Montant réclamé trois fois supérieur au devis indépendant. Suspicion de surfacturation.',                                                                             'VEHICLE_DAMAGE', 'carrosserie, vitres, intérieur',                   7700.00,  'REJECTED', 'Fraude présumée : devis gonflé, rapport d''expertise contradictoire.', 'TOUS_RISQUES', 0.88, 2900,  '2024-11-18'),
('Abir Gafsi',             'Véhicule déjà déclaré sinistré pour les mêmes dommages auprès d''une autre compagnie.',                                                                               'VEHICLE_DAMAGE', 'capot, ailes, pare-choc avant',                   5500.00,  'REJECTED', 'Double assurance non déclarée : sinistre déjà indemnisé par un autre assureur.', 'TOUS_RISQUES', 0.85, 3400,  '2024-12-28'),

-- ═══ THEFT (30) ═══

-- APPROVED (18)
('Hatem Ben Nasr',         'Vol de smartphone iPhone 14 dans un café à Tunis. Téléphone posé sur la table, volé en un instant.',                                                                  'THEFT', 'smartphone iPhone 14',                              3100.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.09, 2800,  '2024-01-18'),
('Imen Rekik',             'Vol de sac à main contenant portefeuille, clés et smartphone Samsung S23.',                                                                                           'THEFT', 'sac, portefeuille, smartphone Samsung',             2900.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.11, 3100,  '2024-02-08'),
('Nizar Haddad',           'Effraction dans le véhicule : laptop MacBook Pro volé depuis le siège arrière.',                                                                                      'THEFT', 'laptop MacBook Pro',                                8500.00,  'APPROVED',        NULL, 'TOUS_RISQUES',    0.14, 4200,  '2024-02-25'),
('Sabria Ben Amor',        'Vol de moto 125cc garée dans la rue, disparue du jour au lendemain.',                                                                                                 'THEFT', 'moto 125cc',                                        3800.00,  'APPROVED',        NULL, 'TOUS_RISQUES',    0.10, 5600,  '2024-03-12'),
('Mehdi Guesmi',           'Cambriolage domicile : TV, ordinateur portable et bijoux volés.',                                                                                                     'THEFT', 'TV, ordinateur portable, bijoux',                  5200.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.08, 4800,  '2024-03-28'),
('Khaoula Ferchichi',      'Vol de vélo électrique depuis le couloir de l''immeuble.',                                                                                                            'THEFT', 'vélo électrique',                                  2400.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.07, 2600,  '2024-04-09'),
('Anis Baldi',             'Smartphone Xiaomi Redmi Note 12 volé dans le bus.',                                                                                                                   'THEFT', 'smartphone Xiaomi Redmi Note 12',                   900.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.06, 1900,  '2024-04-22'),
('Hela Rouissi',           'Cambriolage avec effraction : réfrigérateur, machine à laver et TV emportés.',                                                                                        'THEFT', 'réfrigérateur, machine à laver, TV',              4800.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.09, 5100,  '2024-05-07'),
('Skander Ben Youssef',    'Vol de PC gaming (ASUS ROG) dans le bureau pendant une conférence.',                                                                                                  'THEFT', 'PC gaming ASUS ROG',                                3800.00,  'APPROVED',        NULL, 'MULTIRISQUE_PRO', 0.12, 3400,  '2024-05-24'),
('Marwa Jlassi',           'Effraction dans voiture : sac à dos, iPad et contenu du vide-poche.',                                                                                                 'THEFT', 'sac à dos, iPad',                                  2100.00,  'APPROVED',        NULL, 'TOUS_RISQUES',    0.10, 2900,  '2024-06-10'),
('Chokri Chaabane',        'Vol de montre de luxe (Seiko Prospex) dans un vestiaire de salle de sport.',                                                                                         'THEFT', 'montre de luxe Seiko',                              1800.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.08, 2200,  '2024-06-27'),
('Samira Frikha',          'Moto 50cc volée en plein jour devant le domicile.',                                                                                                                   'THEFT', 'moto 50cc',                                        2300.00,  'APPROVED',        NULL, 'TOUS_RISQUES',    0.07, 4500,  '2024-07-14'),
('Othman Khemiri',         'Vol d''un PC bureau (Core i5 16 Go) lors d''un déménagement.',                                                                                                       'THEFT', 'PC bureau Core i5',                                1900.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.09, 3000,  '2024-07-30'),
('Ranim Ouerghi',          'Smartphone Samsung Galaxy S24 arraché dans la rue par un voleur à la tire.',                                                                                          'THEFT', 'smartphone Samsung Galaxy S24',                    3250.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.10, 2100,  '2024-08-16'),
('Lotfi Amri',             'Cambriolage d''appartement : bijoux en or, argent liquide et smartphone volés.',                                                                                      'THEFT', 'bijoux en or, espèces, smartphone',               6500.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.12, 5800,  '2024-09-02'),
('Chaima Saidi',           'Vol de iPhone 15 Pro sur une table de restaurant.',                                                                                                                   'THEFT', 'smartphone iPhone 15 Pro',                         4200.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.08, 2400,  '2024-09-19'),
('Farid Mabrouk',          'Vélo électrique volé depuis le garage de l''immeuble résidentiel.',                                                                                                   'THEFT', 'vélo électrique',                                  2600.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.06, 2800,  '2024-10-06'),
('Abdelkarim Slama',       'Vol de matériel informatique professionnel (laptop + disque dur externe) depuis le bureau.',                                                                          'THEFT', 'laptop professionnel, disque dur externe',         5100.00,  'APPROVED',        NULL, 'MULTIRISQUE_PRO', 0.11, 3700,  '2024-10-22'),

-- PENDING_REVIEW (6)
('Rim Baccouche',          'Vol de bijoux déclaré tardivement. Aucune preuve de propriété fournie.',                                                                                              'THEFT', 'bijoux',                                           4500.00,  'PENDING_REVIEW',  NULL, 'MULTIRISQUE_HAB', 0.42, 3200,  '2024-04-15'),
('Moez Lahmar',            'Vol de moto 250cc. Pas de plainte déposée. Valeur déclarée supérieure au marché.',                                                                                    'THEFT', 'moto 250cc',                                       9000.00,  'PENDING_REVIEW',  NULL, 'TOUS_RISQUES',    0.48, 4800,  '2024-07-05'),
('Dorra Slimi',            'Cambriolage allégué sans traces d''effraction. Montant très élevé.',                                                                                                  'THEFT', 'TV, ordinateur, bijoux, appareils photo',         12500.00,  'PENDING_REVIEW',  NULL, 'MULTIRISQUE_HAB', 0.55, 5600,  '2024-08-28'),
('Sofien Zribi',           'Vol de smartphone déclaré deux semaines après l''incident.',                                                                                                          'THEFT', 'smartphone iPhone 14',                              3100.00,  'PENDING_REVIEW',  NULL, 'MULTIRISQUE_HAB', 0.38, 2700,  '2024-10-14'),
('Nesrine Mhadhbi',        'Vol de PC gaming avec facture d''achat incohérente avec le modèle déclaré.',                                                                                          'THEFT', 'PC gaming',                                        4800.00,  'PENDING_REVIEW',  NULL, 'MULTIRISQUE_PRO', 0.51, 3900,  '2024-11-28'),
('Jamel Guizani',          'Moto 125cc : vol déclaré mais retrouvée endommagée dans une décharge. Dossier ambigu.',                                                                               'THEFT', 'moto 125cc',                                       4000.00,  'PENDING_REVIEW',  NULL, 'TOUS_RISQUES',    0.44, 4200,  '2025-01-20'),

-- REJECTED (6)
('Hanene Ezzine',          'Vol déclaré mais CCTV du voisinage montre le propriétaire avec l''objet après la date déclarée.',                                                                     'THEFT', 'smartphone',                                       3100.00,  'REJECTED', 'Fraude : enregistrement vidéo contredit la déclaration de vol.', 'MULTIRISQUE_HAB', 0.92, 1800,  '2024-03-05'),
('Nacer Sahnoun',          'Vol de bijoux : l''évaluation indépendante révèle des objets de très faible valeur gonflée.',                                                                         'THEFT', 'bijoux',                                           8000.00,  'REJECTED', 'Fraude : valeur déclarée 8× supérieure à l''expertise indépendante.', 'MULTIRISQUE_HAB', 0.87, 2200,  '2024-05-18'),
('Emna Bejaoui',           'Contrat souscrit 3 jours avant la déclaration de vol. Délai de carence non respecté.',                                                                                'THEFT', 'laptop, smartphone',                               7400.00,  'REJECTED', 'Délai de carence de 30 jours non expiré à la date du sinistre.', 'MULTIRISQUE_HAB', 0.68, 1600,  '2024-07-22'),
('Seifeddine Belaid',      'Objet déclaré volé retrouvé en vente sur Tayara.tn au nom de l''assuré.',                                                                                            'THEFT', 'PC gaming',                                        3800.00,  'REJECTED', 'Fraude prouvée : objet retrouvé en revente par l''assuré lui-même.', 'MULTIRISQUE_PRO', 0.96, 2100,  '2024-09-15'),
('Lobna Trabelsi',         'Vol de moto déclaré mais enregistrement de transfert de propriété trouvé 2 jours avant.',                                                                             'THEFT', 'moto 125cc',                                       3800.00,  'REJECTED', 'Fraude : moto vendue avant la date de vol déclarée.', 'TOUS_RISQUES',    0.89, 2500,  '2024-11-10'),
('Ghassen Ben Hadj',       'Smartphone volé : modèle non couvert par l''extension vol du contrat souscrit.',                                                                                      'THEFT', 'smartphone Samsung S23',                            2700.00,  'REJECTED', 'Exclusion contractuelle : vol de téléphone portable non inclus dans cette formule.', 'TIERS_PLUS',     0.30, 1900,  '2024-12-22'),

-- ═══ PROPERTY_DAMAGE (25) ═══

-- APPROVED (15)
('Afef Ben Slama',         'Dégât des eaux : fuite du voisin du dessus, plafond et murs du salon inondés.',                                                                                      'PROPERTY_DAMAGE', 'plafond, murs salon',                            2800.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.07, 3600,  '2024-01-25'),
('Tarek Missaoui',         'Bris de vitre : fenêtre du séjour cassée par une balle perdue pendant un match.',                                                                                     'PROPERTY_DAMAGE', 'fenêtre séjour',                                  450.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.05, 1400,  '2024-02-12'),
('Wissem Ben Abdallah',    'Vandalisme : façade de commerce dégradée, vitrines brisées, graffitis.',                                                                                              'PROPERTY_DAMAGE', 'façade, vitrines',                               3200.00,  'APPROVED',        NULL, 'MULTIRISQUE_PRO', 0.09, 4100,  '2024-03-01'),
('Hanen Fenniche',         'Incendie cuisine : appareils électroménagers et meubles détruits. Feu maîtrisé rapidement.',                                                                         'PROPERTY_DAMAGE', 'cuisine, électroménager, mobilier',               8500.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.11, 7200,  '2024-03-18'),
('Firas Touil',            'Grêle : toiture de villa partiellement endommagée, gouttières arrachées.',                                                                                            'PROPERTY_DAMAGE', 'toiture, gouttières',                            3800.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.06, 5400,  '2024-04-04'),
('Yosra Baccar',           'Tempête : arbre tombé sur clôture et voiture garée dans le jardin.',                                                                                                  'PROPERTY_DAMAGE', 'clôture, jardin',                                1200.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.08, 3200,  '2024-04-21'),
('Oussama Ayari',          'Dégât des eaux complet : infiltration toiture, appartement entier touché.',                                                                                           'PROPERTY_DAMAGE', 'appartement complet',                            7500.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.10, 8600,  '2024-05-08'),
('Saoussen Ben Romdhane',  'Effondrement partiel d''un mur de soutènement suite aux pluies.',                                                                                                    'PROPERTY_DAMAGE', 'mur de soutènement',                             4200.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.09, 6100,  '2024-05-25'),
('Nader Achour',           'Bris de porte vitrée double vitrage (entrée principale du commerce).',                                                                                                'PROPERTY_DAMAGE', 'porte vitrée entrée',                             750.00,  'APPROVED',        NULL, 'MULTIRISQUE_PRO', 0.05, 2000,  '2024-06-11'),
('Lobna Ghariani',         'Incendie dépendance : garage brûlé partiellement, voiture légèrement touchée.',                                                                                      'PROPERTY_DAMAGE', 'garage, carrosserie véhicule',                   5100.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.12, 6800,  '2024-06-28'),
('Ala Ben Hamida',         'Inondation locale commerciale suite à rupture de canalisation externe.',                                                                                              'PROPERTY_DAMAGE', 'local commercial, stock',                         9200.00,  'APPROVED',        NULL, 'MULTIRISQUE_PRO', 0.08, 9400,  '2024-07-15'),
('Kawthar Jerbi',          'Vandalisme véhicule stationné : carrosserie rayée, rétroviseurs brisés.',                                                                                             'PROPERTY_DAMAGE', 'carrosserie véhicule, rétroviseurs',               1100.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.07, 2700,  '2024-08-01'),
('Iheb Khmiri',            'Grêle intensive : multiples bris de tuiles, velux cassé, infiltrations.',                                                                                             'PROPERTY_DAMAGE', 'tuiles, velux, plafond',                          4600.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.09, 6300,  '2024-08-18'),
('Myriam Boughzala',       'Fuite importante : dégât des eaux murs et sol chambre principale.',                                                                                                   'PROPERTY_DAMAGE', 'murs chambre, sol parquet',                       3100.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.07, 4400,  '2024-09-04'),
('Hamza Zoghlami',         'Incendie partiel salon : court-circuit électrique, mobilier et murs endommagés.',                                                                                    'PROPERTY_DAMAGE', 'salon, mobilier, murs',                           6800.00,  'APPROVED',        NULL, 'MULTIRISQUE_HAB', 0.10, 7500,  '2024-09-21'),

-- PENDING_REVIEW (5)
('Amine Hadj Taieb',       'Incendie allégué d''entrepôt : montant très élevé, cause indéterminée.',                                                                                             'PROPERTY_DAMAGE', 'entrepôt complet, stock, équipements',           48000.00,  'PENDING_REVIEW',  NULL, 'MULTIRISQUE_PRO', 0.48, 14200, '2024-04-30'),
('Rym Hammami',            'Dégât des eaux sur appartement complet. Relation propriétaire/locataire floue.',                                                                                      'PROPERTY_DAMAGE', 'appartement complet',                           11000.00,  'PENDING_REVIEW',  NULL, 'MULTIRISQUE_HAB', 0.39, 8800,  '2024-07-20'),
('Bassem Karoui',          'Inondation suite à tempête. Montant réclamé inclut équipements anciens à neuf.',                                                                                      'PROPERTY_DAMAGE', 'habitation, mobilier, équipements',             15500.00,  'PENDING_REVIEW',  NULL, 'MULTIRISQUE_HAB', 0.43, 10300, '2024-09-10'),
('Yasmine Hmidi',          'Séisme : fissures importantes. Expertise structurelle nécessaire.',                                                                                                   'PROPERTY_DAMAGE', 'structure bâtiment, murs porteurs',             22000.00,  'PENDING_REVIEW',  NULL, 'MULTIRISQUE_HAB', 0.31, 12600, '2024-11-25'),
('Mahdi Ben Fredj',        'Incendie commerce : cause suspectée volontaire selon voisins. Enquête en cours.',                                                                                     'PROPERTY_DAMAGE', 'commerce, stock, équipements',                  35000.00,  'PENDING_REVIEW',  NULL, 'MULTIRISQUE_PRO', 0.62, 16800, '2025-01-15'),

-- REJECTED (5)
('Leila Bouzid',           'Dommages existants avant la souscription du contrat, non déclarés.',                                                                                                  'PROPERTY_DAMAGE', 'murs, plafond salon',                             5400.00,  'REJECTED', 'Dommages préexistants à la souscription non déclarés lors de la visite d''état des lieux.', 'MULTIRISQUE_HAB', 0.55, 2400,  '2024-05-15'),
('Ridha Nouri',            'Incendie déclaré mais rapport des pompiers indique cause volontaire.',                                                                                                'PROPERTY_DAMAGE', 'habitation, garage',                             28000.00,  'REJECTED', 'Incendie volontaire confirmé par rapport officiel des pompiers — exclusion contractuelle.', 'MULTIRISQUE_HAB', 0.94, 3100,  '2024-08-08'),
('Meriem Oueslati',        'Contrat habitation ne couvre pas les dommages aux dépendances séparées.',                                                                                             'PROPERTY_DAMAGE', 'dépendance, grange',                              8200.00,  'REJECTED', 'Dépendances séparées non incluses dans les garanties du contrat souscrit.', 'MULTIRISQUE_HAB', 0.28, 2100,  '2024-10-05'),
('Hichem Beji',            'Double déclaration du même sinistre sous deux contrats différents.',                                                                                                  'PROPERTY_DAMAGE', 'commerce, équipements',                          18500.00,  'REJECTED', 'Double déclaration détectée : sinistre déjà indemnisé par un autre contrat.', 'MULTIRISQUE_PRO', 0.83, 2800,  '2024-11-20'),
('Zohra Cherif',           'Travaux de rénovation mal exécutés : non-couverture hors sinistre accidentel.',                                                                                      'PROPERTY_DAMAGE', 'carrelage, canalisations',                        4100.00,  'REJECTED', 'Dommage résultant de travaux défectueux, non assimilable à un sinistre accidentel couvert.', 'MULTIRISQUE_HAB', 0.35, 1900,  '2024-12-14');
